
FMT = '%Y-%m-%d'

File_Info_Dict = [
        {
            'file_name' :  'genpak releases - current.xlsx',
            'interest_field_list':  ['GP OH', 'On Order', 'Target Date', 'WIP', 'Ship Qy', 'Del Date', ],
            'header_row' : 6,
            'first_key_name' : 'Item',
            'second_key_name' : '',
            'datetime_fmt' : FMT,
            'dict_level' : 1,
        },
        {
            'file_name' : 'superpufft 2020 pricing  inventory report may 27, 2021.xlsx',
            'interest_field_list': ['Total/KG', 'Next Available date & Quantity/KG' ],
            'header_row' : 7,
            'first_key_name' : 'Super Pufft Code',
            'second_key_name' : '',
            'datetime_fmt' : FMT,
            'dict_level' : 1,            
        },
        {
            'file_name' : 'bom list.xlsx',
            'interest_field_list': ["Unit of Measure Code", "Quantity", "Scrap %" ,],
            'header_row' : 1,
            'first_key_name' : 'Production BOM No.',
            'second_key_name' : 'No.',
            'datetime_fmt' : FMT,
            'dict_level' : 2,            
        },
        {
            'file_name' : 'customer order list.xlsx',
            'interest_field_list': [
                                         "Document Type",
                                        "Sell-to Customer No.",
                                        "Type" ,
                                        "Quantity",
                                        "Shipment Date",
                                        "Outstanding Quantity" ,
                                        "Unit of Measure Code",
                                        ],
            'header_row' : 1,
            'first_key_name' : 'No.',
            'second_key_name' : 'Document No.',
            'datetime_fmt' : FMT,
            'dict_level' : 1,            
        },
        {
            'file_name' : 'purchase lines.xlsx',
            'interest_field_list': [
                                        "Promised Receipt Date",
                                        "Outstanding Quantity",
                                        "Requested Receipt Date" ,
                                    ],
            'header_row' : 1,
            'first_key_name' : 'No.',
            'second_key_name' : 'seq',
            'datetime_fmt' : FMT,
            'dict_level' : 1,        
        },
        {
            'file_name' : 'item list.xlsx',
            'interest_field_list': [
                                        'Duty Class',
                                        'W1',
                                        'W2',
                                        'Description',
                                        'Base Unit of Measure' ,
                                        'Vendor No.',
                                        'Item Category Code',
                                        'Quantity on Hand',
                                        ],
            'header_row' : 1,
            'first_key_name' : 'No.',
            'second_key_name' : '',
            'datetime_fmt' : FMT,
            'dict_level' : 1,
        },
    ]